[config]
default_to_workspace = true
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

[tasks.default]
alias = "serve"

[tasks.cargo-fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]

[tasks.fmt-all]
script = '''
leptosfmt .
cargo fmt --all
cargo clippy --fix -- -D warnings
'''

[tasks.check]
script = '''
leptosfmt --check .
cargo fmt --all --check
cargo clippy -- -D warnings
'''

[tasks.leptos-fmt]
install_crate = "leptosfmt"
command = "leptosfmt"
args = ["."]

[tasks.format]
dependencies = ["cargo-format", "leptos-format"]

[tasks.fmt]
alias = "format"

[tasks.prebuild]
command = "npx"
args = ["tailwindcss", "-i", "./input.css", "-o", "./style/output.css"]

[tasks.build]
dependencies = ["prebuild"]
install_crate = { crate_name = "cargo-leptos", binary = "cargo", test_arg = [
    "leptos",
    "--version",
], version = "0.2.12" }
command = "cargo"
args = ["leptos", "serve", "-r"]

[tasks.serve]
command = "cargo"
args = ["leptos", "watch", "--features", "development", "--hot-reload"]
