[config]
default_to_workspace = true
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

[tasks.default]
alias = "serve"

[tasks.cargo-fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]

[tasks.fmt-all]
script = '''
leptosfmt .
cargo fmt --all
cargo clippy --fix -- -D warnings
'''
[tasks.check-leptos]
command = "leptosfmt"
args = ["--check", "."]

[tasks.check-fmt]
command = "cargo"
args = ["fmt", "--all", "--check"]

[tasks.check-clippy]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.check]
dependencies = ["check-fmt", "check-leptos", "check-clippy"]

[tasks.leptos-fmt]
install_crate = "leptosfmt"
command = "leptosfmt"
args = ["."]

[tasks.format]
dependencies = ["cargo-format", "leptos-format"]

[tasks.fmt]
alias = "format"

[tasks.build]
command = "cargo"
args = ["leptos", "build", "-r", "--features", "csr"]

[tasks.serve]
command = "cargo"
args = ["leptos", "watch", "--features", "development", "--hot-reload"]
