name: clippy
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "src/**/**.rs"
      - "style/**.scss"

jobs:
  check-fmt:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly-2024-03-08
      - uses: Swatinem/rust-cache@v2
      - name: checks
        run: |
          cargo fmt --all --check

  check-leptos:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly-2024-03-08
      - name: Cache .cargo and target
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-cargo-leptos-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-leptos-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-leptos
      - name: Install LeptosFmt
        run: cargo install leptosfmt --version 0.1.18
      - name: Check LeptosFmt
        run: leptosfmt --check .

  check-clippy:
    needs: [fmt, leptosfmt]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly-2024-03-08
      - uses: Swatinem/rust-cache@v2
      - name: cargo clippy
        run: |
          clippy --features=csr -- -D warnings
