name: Publish to GitHub Pages
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - riir

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  build:
    needs: [checks]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-03-08
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - uses: jetli/trunk-action@v0.4.0
        with:
          version: 'v0.18.8'
      - name: Install cargo-make
        run: |
          cargo install cargo-make --version 0.37.9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install NodeJs deps
        run: npm install
      - name: build
        run: |
          cargo make build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
